### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by jeammimi** [nleng/DNA-replication#1]
Hello, 
First thanks for sharing your code!
I have a question regarding the running time od DNA_metropolis:
On the website it takes like 10 second to generate the configuration,
but when I execute the code on my computer it is a lot longer:
for one iteration it takes about 30 s and by default you set the number
of iterations to 10001.
Why such a difference?

**Comment by nleng** [comment]
Hi,
thank you for you interest in our project. We use two separate simulations, one for 1-dimensional simulation of fork progression on DNA, which takes about 20-40 seconds. The other is a 3D monte carlo simulation of DNA, which is much slower because of the great number of beads which constitute the polymer chain. It is only used to generate realistic configuration on which the fork positions from the first simulation can be projected, not to create real-time DNA movement. To get a configuration near thermal equilibrium, we usually run the DNA simulation for a few days until the energy converges.

The discrepancy to the website is due to the fact that on the website the 5-10 seconds are needed only to create the images, i.e. calculate the 3D fork positions, but the DNA-configuration is not simulated again every time. We have stored configurations of all possible combinations of eu/fac/het-chromation on the server, which are then used to create the images. 
Best regard,

**Comment by jeammimi** [comment]
It was too fast to be true :)
In the references that you mention for the DNA metropolis, they use Molecular dynamics to 
equilibrate and sample. 
Did you have the time to compare with your Monte carlo approach?
Or more generaly was there a specific reason te choose Monte-Carlo?
Thanks

**Comment by jeammimi** [comment]
It was too fast to be true :)
In the references that you mention for the DNA metropolis, they use Molecular dynamics to 
equilibrate and sample. 
Did you have the time to compare with your Monte carlo approach?
Or more generaly was there a specific reason te choose Monte-Carlo?
Thanks

**Comment by jeammimi** [comment]
It was too fast to be true :)
In the references that you mention for the DNA metropolis, they use Molecular dynamics to 
equilibrate and sample. 
Did you have the time to compare with your Monte carlo approach?
Or more generaly was there a specific reason te choose Monte-Carlo?
Thanks

**Comment by nleng** [comment]
The project was started by someone else and I am not sure why he decided to use Monte Carlo over MD simulations. I think one advantage is that in MD you integrate over time, so every step is usually 1-2 femto seconds. As far as I understand you don't really have a linear time in MC simulations since each step only depends on the probability calculated from energy difference. So one MC step could be 1000 MD steps and MC will converge relatively fast even if you place all beads randomly. On the other hand with GPU usage MD is quite fast too nowadays, but I did not compare.

**Comment by jeammimi** [comment]
Ok, thanks for all these informations!
